# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: '2.1'

volumes:
  keys:

services:

  # -------------=== shell ===-------------
  shell:
    image: hyperledger/sawtooth-all:1.0
    container_name: shell-default
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

  # -------------=== settings tp ===-------------
  settings-tp-0:
    container_name: settings-tp-0
    image: hyperledger/sawtooth-settings-tp:1.0
    command: settings-tp -v --connect tcp://validator-0:4004


  settings-tp-1:
    container_name: settings-tp-1
    image: hyperledger/sawtooth-settings-tp:1.0
    command: settings-tp -v --connect tcp://validator-1:4004

  settings-tp-2:
    container_name: settings-tp-2
    image: hyperledger/sawtooth-settings-tp:1.0
    command: settings-tp -v --connect tcp://validator-2:4004


  settings-tp-3:
    container_name: settings-tp-3
    image: hyperledger/sawtooth-settings-tp:1.0
    command: settings-tp -v --connect tcp://validator-3:4004

  settings-tp-4:
    container_name: settings-tp-4
    image: hyperledger/sawtooth-settings-tp:1.0
    command: settings-tp -v --connect tcp://validator-4:4004


  # -------------=== simple tp ===-------------
  simple-tp-python-0:
    image: szeshun/sawtooth-simple-tp:latest
    container_name: simple-tp-python-default-0
    expose:
      - 4004
    volumes:
      - '../../../src/:/project/'
    entrypoint: simple-tp-python -vv -C tcp://validator-0:4004
    stop_signal: SIGKILL


  simple-tp-python-1:
    image: szeshun/sawtooth-simple-tp:latest
    container_name: simple-tp-python-default-1
    expose:
      - 4004
    volumes:
      - '../../../src/:/project/'
    entrypoint: simple-tp-python -v -C tcp://validator-1:4004
    stop_signal: SIGKILL

  simple-tp-python-2:
    image: szeshun/sawtooth-simple-tp:latest
    container_name: simple-tp-python-default-2
    expose:
      - 4004
    volumes:
      - '../../../src/:/project/'
    entrypoint: simple-tp-python -v -C tcp://validator-2:4004
    stop_signal: SIGKILL


  simple-tp-python-3:
    image: szeshun/sawtooth-simple-tp:latest
    container_name: simple-tp-python-default-3
    expose:
      - 4004
    volumes:
      - '../../../src/:/project/'
    entrypoint: simple-tp-python -v -C tcp://validator-3:4004
    stop_signal: SIGKILL

  simple-tp-python-4:
    image: szeshun/sawtooth-simple-tp:latest
    container_name: simple-tp-python-default-4
    expose:
      - 4004
    volumes:
      - '../../../src/:/project/'
    entrypoint: simple-tp-python -v -C tcp://validator-4:4004
    stop_signal: SIGKILL


  # -------------=== validator ===-------------
  validator-0:
    container_name: validator-0
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
      - 8800
    ports:
      - '4004:4004'
    volumes:
      - keys:/shared_keys
    working_dir: /root
    command: |
      bash -c "
            sawadm keygen validator-1 && \
            sawadm keygen validator-2 && \
            sawadm keygen validator-3 && \
            sawadm keygen validator-4 && \
            sawadm keygen && \

      sawset genesis \
               -k /etc/sawtooth/keys/validator.priv \
               -o config-genesis.batch && \

      sawset proposal create \
                -k /etc/sawtooth/keys/validator.priv \
                sawtooth.consensus.algorithm.name=raft \
                sawtooth.consensus.algorithm.version=0.1 \
                sawtooth.consensus.raft.peers=\\['\"'$$(cat /etc/sawtooth/keys/validator.pub )'\"','\"'$$(cat /etc/sawtooth/keys/validator-1.pub )'\"','\"'$$(cat /etc/sawtooth/keys/validator-2.pub )'\"','\"'$$(cat /etc/sawtooth/keys/validator-3.pub )'\"','\"'$$(cat /etc/sawtooth/keys/validator-4.pub )'\"'\\] \
                sawtooth.consensus.raft.period=1 \
                sawtooth.publisher.max_batches_per_block=100 \
                sawtooth.validator.max_transactions_per_block=100 \
                -o config.batch && \

      sawadm genesis \
               config-genesis.batch config.batch && \

      mv /etc/sawtooth/keys/validator-* /shared_keys && \
             echo $$(cat /etc/sawtooth/keys/validator.pub); \
             sawtooth-validator -v \
                 --endpoint tcp://validator-0:8800 \
                 --bind component:tcp://eth0:4004 \
                 --bind network:tcp://eth0:8800 \
                 --bind consensus:tcp://eth0:5050 \
                 --peering dynamic \
                 --scheduler parallel \
      "

  validator-1:
    container_name: validator-1
    image: hyperledger/sawtooth-validator:1.0
    volumes:
      - keys:/shared_keys
    expose:
      - 4004
      - 8800
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen &&
          sawtooth keygen my_key
        fi;
        sawtooth-validator -vvv --endpoint tcp://validator-1:8800 --bind component:tcp://eth0:4004 --bind network:tcp://eth0:8800 --bind consensus:tcp://eth0:5050 --peering dynamic --seeds tcp://validator-0:8800 
      "
    depends_on:
      - validator-0


  validator-2:
    container_name: validator-2
    image: hyperledger/sawtooth-validator:1.0
    volumes:
      - keys:/shared_keys
    expose:
      - 4004
      - 8800
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen &&
          sawtooth keygen my_key
        fi;
        sawtooth-validator -vvv --endpoint tcp://validator-2:8800 --bind component:tcp://eth0:4004 --bind network:tcp://eth0:8800 --bind consensus:tcp://eth0:5050 --peering dynamic --seeds tcp://validator-0:8800
      "
    depends_on:
      - validator-0      

  validator-3:
    container_name: validator-3
    image: hyperledger/sawtooth-validator:1.0
    volumes:
      - keys:/shared_keys
    expose:
      - 4004
      - 8800
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen &&
          sawtooth keygen my_key
        fi;
        sawtooth-validator -vvv --endpoint tcp://validator-3:8800 --bind component:tcp://eth0:4004 --bind network:tcp://eth0:8800 --bind consensus:tcp://eth0:5050 --peering dynamic --seeds tcp://validator-0:8800
      "
    depends_on:
      - validator-0

  validator-4:
    container_name: validator-4
    image: hyperledger/sawtooth-validator:1.0
    volumes:
      - keys:/shared_keys
    expose:
      - 4004
      - 8800
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen &&
          sawtooth keygen my_key
        fi;
        sawtooth-validator -vvv --endpoint tcp://validator-4:8800 --bind component:tcp://eth0:4004 --bind network:tcp://eth0:8800 --bind consensus:tcp://eth0:5050 --peering dynamic --seeds tcp://validator-0:8800
      "
    depends_on:
      - validator-0


  # -------------=== rest-api ===-------------
  rest-api-0:
    container_name: rest-api-0
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8000:8008'
    depends_on:
      - validator-0
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-0:4004 \
          --bind rest-api-0:8008
      "
    stop_signal: SIGKILL

  rest-api-1:
    container_name: rest-api-1
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8001:8008'
    depends_on:
      - validator-1
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-1:4004 \
          --bind rest-api-1:8008
      "
    stop_signal: SIGKILL


  rest-api-2:
    container_name: rest-api-2
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8002:8008'
    depends_on:
      - validator-2
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-2:4004 \
          --bind rest-api-2:8008
      "
    stop_signal: SIGKILL

  rest-api-3:
    container_name: rest-api-3
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8003:8008'
    depends_on:
      - validator-3
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-3:4004 \
          --bind rest-api-3:8008
      "
    stop_signal: SIGKILL

  rest-api-4:
    container_name: rest-api-4
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8004:8008'
    depends_on:
      - validator-4
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-4:4004 \
          --bind rest-api-4:8008
      "
    stop_signal: SIGKILL


# ------------- raft engine ------------------------
  raft-engine-0:
    image: hyperledger/sawtooth-raft-engine:chime
    container_name: sawtooth-raft-engine-0
    command: raft-engine --connect tcp://validator-0:5050 -v
    stop_signal: SIGKILL
    environment:
      RUST_BACKTRACE: full


  raft-engine-1:
    image: hyperledger/sawtooth-raft-engine:chime
    container_name: sawtooth-raft-engine-1
    command: raft-engine --connect tcp://validator-1:5050 -v
    stop_signal: SIGKILL
    environment:
      RUST_BACKTRACE: full

  raft-engine-2:
    image: hyperledger/sawtooth-raft-engine:chime
    container_name: sawtooth-raft-engine-2
    command: raft-engine --connect tcp://validator-2:5050 -v
    stop_signal: SIGKILL
    environment:
      RUST_BACKTRACE: full

  raft-engine-3:
    image: hyperledger/sawtooth-raft-engine:chime
    container_name: sawtooth-raft-engine-3
    command: raft-engine --connect tcp://validator-3:5050 -v
    stop_signal: SIGKILL
    environment:
      RUST_BACKTRACE: full

  raft-engine-4:
    image: hyperledger/sawtooth-raft-engine:chime
    container_name: sawtooth-raft-engine-4
    command: raft-engine --connect tcp://validator-4:5050 -v
    stop_signal: SIGKILL
    environment:
      RUST_BACKTRACE: full