
# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2.1"

volumes:
  keys:

services:

  # -------------=== settings tp ===-------------


  settings-tp-1:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp-1
    expose:
      - 4004
    depends_on:
      - validator-0
    command: |
      bash -c "
        settings-tp -vvv -C tcp://validator-0:4004
      "
    stop_signal: SIGKILL

  settings-tp-2:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp-2
    expose:
      - 4004
    depends_on:
      - validator-1
    command: |
      bash -c "
        settings-tp -vvv -C tcp://validator-1:4004
      "
    stop_signal: SIGKILL

  settings-tp-3:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp-3
    expose:
      - 4004
    depends_on:
      - validator-2
    command: |
      bash -c "
        settings-tp -vvv -C tcp://validator-2:4004
      "
    stop_signal: SIGKILL

  settings-tp-4:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp-4
    expose:
      - 4004
    depends_on:
      - validator-3
    command: |
      bash -c "
        settings-tp -vvv -C tcp://validator-3:4004
      "
    stop_signal: SIGKILL

  settings-tp-5:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp-5
    expose:
      - 4004
    depends_on:
      - validator-4
    command: |
      bash -c "
        settings-tp -vvv -C tcp://validator-4:4004
      "
    stop_signal: SIGKILL


 # -------------=== shell ===-----------------------

  shell:
    image: hyperledger/sawtooth-all:1.0
    container_name: shell-default
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

# -------------=== validators ===-------------
  validator-0:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator-0
    expose:
      - 4004
      - 8800
      - 5050
    volumes:
      - keys:/shared_keys
    working_dir: /root
    command: |
      bash -c "
            sawadm keygen validator-1 && \
            sawadm keygen validator-2 && \
            sawadm keygen validator-3 && \
            sawadm keygen validator-4 && \
            sawadm keygen && \

      sawset genesis \
               -k /etc/sawtooth/keys/validator.priv \
               -o config-genesis.batch && \

      sawset proposal create \
                -k /etc/sawtooth/keys/validator.priv \
                sawtooth.consensus.algorithm.name=raft \
                sawtooth.consensus.algorithm.version=0.1 \
                sawtooth.consensus.raft.peers=\\['\"'$$(cat /etc/sawtooth/keys/validator.pub )'\"','\"'$$(cat /etc/sawtooth/keys/validator-1.pub )'\"','\"'$$(cat /etc/sawtooth/keys/validator-2.pub )'\"','\"'$$(cat /etc/sawtooth/keys/validator-3.pub )'\"','\"'$$(cat /etc/sawtooth/keys/validator-4.pub )'\"'\\] \
                sawtooth.consensus.raft.period=1 \
                sawtooth.publisher.max_batches_per_block=100 \
                sawtooth.validator.max_transactions_per_block=100 \
                -o config.batch && \

      sawadm genesis \
               config-genesis.batch config.batch && \

      mv /etc/sawtooth/keys/validator-* /shared_keys && \
             echo $$(cat /etc/sawtooth/keys/validator.pub); \
             sawtooth-validator -v \
                 --endpoint tcp://validator-0:8800 \
                 --bind component:tcp://eth0:4004 \
                 --bind network:tcp://eth0:8800 \
                 --bind consensus:tcp://eth0:5050 \
                 --peering static \
                 --peers tcp://validator-1:8800,tcp://validator-2:8800,tcp://validator-3:8800,tcp://validator-4:8800 \
                 --scheduler parallel \
      "

    stop_signal: SIGKILL

  validator-1:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator-1
    volumes:
      - keys:/shared_keys
    expose:
      - 4004
      - 8800
      - 5050
    command: |
      bash -c "
       while true;
      do if [ -e /shared_keys/validator-1.pub ];
      then mv /shared_keys/validator-1.priv /etc/sawtooth/keys/validator.priv &&
      mv /shared_keys/validator-1.pub /etc/sawtooth/keys/validator.pub;
      break; fi; sleep 0.5; done; \
      echo $$(cat /etc/sawtooth/keys/validator.pub); \
              sawtooth-validator -v \
                  --endpoint tcp://validator-1:8800 \
                  --bind component:tcp://eth0:4004 \
                  --bind network:tcp://eth0:8800 \
                  --bind consensus:tcp://eth0:5050 \
                  --peering static \
                  --peers tcp://validator-0:8800,tcp://validator-2:8800,tcp://validator-3:8800,tcp://validator-4:8800 \
                  --scheduler parallel \
      "
    stop_signal: SIGKILL



  validator-2:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator-2
    expose:
      - 4004
      - 8800
      - 5050
    volumes:
      - keys:/shared_keys
    command: |
      bash -c "
       while true;
      do if [ -e /shared_keys/validator-2.pub ];
      then mv /shared_keys/validator-2.priv /etc/sawtooth/keys/validator.priv &&
      mv /shared_keys/validator-2.pub /etc/sawtooth/keys/validator.pub;
      break; fi; sleep 0.5; done; \
       echo $$(cat /etc/sawtooth/keys/validator.pub); \

      sawtooth-validator -v \
                 --endpoint tcp://validator-2:8800 \
                 --bind component:tcp://eth0:4004 \
                 --bind network:tcp://eth0:8800 \
                 --bind consensus:tcp://eth0:5050 \
                 --peering static \
                 --peers tcp://validator-0:8800,tcp://validator-1:8800,tcp://validator-3:8800,tcp://validator-4:8800 \
                 --scheduler parallel \

      "
    stop_signal: SIGKILL

  validator-3:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator-3
    expose:
      - 4004
      - 8800
      - 5050
    volumes:
      - keys:/shared_keys
    command: |
      bash -c "
       while true;
      do if [ -e /shared_keys/validator-3.pub ];
      then mv /shared_keys/validator-3.priv /etc/sawtooth/keys/validator.priv &&
      mv /shared_keys/validator-3.pub /etc/sawtooth/keys/validator.pub;
      break; fi; sleep 0.5; done; \
       echo $$(cat /etc/sawtooth/keys/validator.pub); \

      sawtooth-validator -v \
                 --endpoint tcp://validator-3:8800 \
                 --bind component:tcp://eth0:4004 \
                 --bind network:tcp://eth0:8800 \
                 --bind consensus:tcp://eth0:5050 \
                 --peering static \
                 --peers tcp://validator-0:8800,tcp://validator-1:8800,tcp://validator-2:8800,tcp://validator-4:8800 \
                 --scheduler parallel \

      "
    stop_signal: SIGKILL

  validator-4:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator-4
    expose:
      - 4004
      - 8800
      - 5050
    volumes:
      - keys:/shared_keys
    command: |
      bash -c "
       while true;
      do if [ -e /shared_keys/validator-4.pub ];
      then mv /shared_keys/validator-4.priv /etc/sawtooth/keys/validator.priv &&
      mv /shared_keys/validator-4.pub /etc/sawtooth/keys/validator.pub;
      break; fi; sleep 0.5; done; \
       echo $$(cat /etc/sawtooth/keys/validator.pub); \

      sawtooth-validator -v \
                 --endpoint tcp://validator-4:8800 \
                 --bind component:tcp://eth0:4004 \
                 --bind network:tcp://eth0:8800 \
                 --bind consensus:tcp://eth0:5050 \
                 --peering static \
                 --peers tcp://validator-0:8800,tcp://validator-1:8800,tcp://validator-2:8800,tcp://validator-3:8800 \
                 --scheduler parallel \

      "
    stop_signal: SIGKILL





    # -------------=== rest api ===-------------



  rest-api-0:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api-default-1
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-0:4004 \
          --bind rest-api-0:8008
      "
    stop_signal: SIGKILL

  rest-api-1:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api-default-2
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-1:4004 \
          --bind rest-api-1:8008
      "
    stop_signal: SIGKILL

  rest-api-2:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api-default-3
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-2:4004 \
          --bind rest-api-2:8008
      "
    stop_signal: SIGKILL

  rest-api-3:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api-default-4
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-3:4004 \
          --bind rest-api-3:8008
      "
    stop_signal: SIGKILL

  rest-api-4:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api-default-5
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-4:4004 \
          --bind rest-api-4:8008
      "
    stop_signal: SIGKILL



# ------------- raft engine ------------------------



  raft-engine-0:
    image: hyperledger/sawtooth-raft-engine:chime
    container_name: sawtooth-raft-engine-0
    command: raft-engine --connect tcp://validator-0:5050 -v
    stop_signal: SIGKILL
    environment:
      RUST_BACKTRACE: full


  raft-engine-1:
    image: hyperledger/sawtooth-raft-engine:chime
    container_name: sawtooth-raft-engine-1
    command: raft-engine --connect tcp://validator-1:5050 -v
    stop_signal: SIGKILL
    environment:
      RUST_BACKTRACE: full

  raft-engine-2:
    image: hyperledger/sawtooth-raft-engine:chime
    container_name: sawtooth-raft-engine-2
    command: raft-engine --connect tcp://validator-2:5050 -v
    stop_signal: SIGKILL
    environment:
      RUST_BACKTRACE: full

  raft-engine-3:
    image: hyperledger/sawtooth-raft-engine:chime
    container_name: sawtooth-raft-engine-3
    command: raft-engine --connect tcp://validator-3:5050 -v
    stop_signal: SIGKILL
    environment:
      RUST_BACKTRACE: full

  raft-engine-4:
    image: hyperledger/sawtooth-raft-engine:chime
    container_name: sawtooth-raft-engine-4
    command: raft-engine --connect tcp://validator-4:5050 -v
    stop_signal: SIGKILL
    environment:
      RUST_BACKTRACE: full

